name: moengage_flutter
description: Flutter Plugin for MoEngage Platform. MoEngage is an Intelligent Customer Engagement Platform
version: 1.0.1
author: MoEngage Inc<mobiledevs@moengage.com>
homepage: https://www.moengage.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.moengage.flutter
    pluginClass: MoEngageFlutterPlugin

